apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ubuntu 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu 
    spec:
      containers:
        - name: ubuntu 
          image: devregistrycontainer.azurecr.io/ubuntu
          ports:
          - containerPort: 3310